run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - gocritic
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: false
  revive:
    rules:
      - name: exported
        severity: warning
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - diagnostic
      - style

issues:
  exclude-dirs:
    - vendor
    - dist
    - node_modules
  max-issues-per-linter: 50
  max-same-issues: 5
